PASSING_OVERALL_SCORE = 4.0
MIN_NUMERIC_SCORE = 4.0
MAX_REVISION_ATTEMPTS = 2

DEFAULT_MODEL = "gpt-3.5-turbo"
SUPPORTED_MODELS = ("gpt-3.5-turbo", "gpt-4o-mini")
STRUCTURED_OUTPUT_MODELS = ("gpt-4o-mini",)
